name: CI

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build it
      run: |
        npm install
        npm run dist
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jitsi-meet-amd64.deb
        path: dist/jitsi-meet-amd64.deb
  build-mac:
    name: macOS
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build it
      run: |
        npm install
        npm run lint
        npm run dist
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jitsi-meet.dmg
        path: dist/jitsi-meet.dmg
  build-windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build it
      run: |
        npm install
        npm run dist
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jitsi-meet.exe
        path: dist/jitsi-meet.exe
