name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, '[build]')"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: sudo apt-get install libx11-dev zlib1g-dev libpng-dev libxtst-dev
    - name: Build it
      run: |
        npm install
        npm run dist
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: jitsi-meet-amd64.deb
        path: dist/jitsi-meet-amd64.deb
  build-windows:
    name: Windows
    runs-on: windows-2019
    if: "contains(github.event.head_commit.message, '[build]')"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build it
      run: |
        npm install
        npm run dist
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: jitsi-meet.exe
        path: dist/jitsi-meet.exe
  build-mac:
    name: macOS
    runs-on: macos-10.15
    if: "contains(github.event.head_commit.message, '[build]')"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Fixup Xcode
      # https://github.com/actions/virtual-environments/issues/2557
      run: |
        sudo xcode-select -s "/Applications/Xcode_12.4.app"
        sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
    - name: Build it
      run: |
        npm install
        npm run lint
        npm run dist
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: jitsi-meet.dmg
        path: dist/jitsi-meet.dmg
